### ISSUE TITLE
Strict mod kullanılmalı.

### ISSUE THREAD

**Issue by abdullah** [eneserdogan/iftar#1]
Hata kaynağı : 

```
let spin = new spinner('%s Güncel veriler alınıyor.');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/iftar/bin/iftar.js:2:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Zaman ayırıp uygulamayı yazdığınız için teşekkürler.

**Comment by eneserdogan** [comment]
Geri dönüş için teşekkür ederim, düzeltmeyi yaptım 👍🏻

``` bash
[sudo] npm update -g iftar
```
